package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"net/url"
	"path"
	"sort"
	"strings"
)

func main() {
	var buf bytes.Buffer
	buf.WriteString(strings.TrimLeft(authInfo, "\n"))
	buf.WriteString("\n# 目录\n")
	readDir(".", root, &buf)
	buf.WriteString(footer)
	err := ioutil.WriteFile("README.md", buf.Bytes(), 0644)
	checkErr(err)
}

func readDir(dirname string, level int, buf *bytes.Buffer) {
	fileList, err := ioutil.ReadDir(dirname)
	checkErr(err)
	sort.Slice(fileList, func(i, j int) bool {
		if fileList[i].IsDir() == fileList[j].IsDir() {
			return strings.ToLower(fileList[i].Name()) < strings.ToLower(fileList[j].Name())
		}
		return fileList[j].IsDir()
	})
	for _, fi := range fileList {
		if validName(fi.Name()) {
			if level == root {
				buf.WriteString("\n")
				if fi.IsDir() {
					buf.WriteString("## ")
				}
			} else {
				buf.WriteString(strings.Repeat("  ", level))
				buf.WriteString("- ")
			}
			buf.WriteString(fmt.Sprintf("[%s](%s)\n",
				fi.Name(),
				url.PathEscape(path.Join(dirname, fi.Name())),
			))
			if fi.IsDir() {
				readDir(path.Join(dirname, fi.Name()), level+1, buf)
			}
		}
	}
}

func validName(name string) bool {
	name = strings.ToLower(name)
	excludeFile := map[string]bool{
		"license": true,
		"go.mod":  true,
		"go.sum":  true,
	}
	return !(excludeFile[name] ||
		strings.HasPrefix(name, ".") ||
		strings.HasSuffix(name, ".md") ||
		strings.HasSuffix(name, ".go"))
}

func checkErr(err error) {
	if err != nil {
		log.Fatalln(err)
	}
}

const root = 0

const authInfo = `
<!--|This file generated by command; DO NOT EDIT.                          |-->
<!--+----------------------------------------------------------------------+-->
<!--|@author    openset <openset.wang@gmail.com>                           |-->
<!--|@link      https://github.com/openset                                 |-->
<!--|@home      https://github.com/openset/books                           |-->
<!--+----------------------------------------------------------------------+-->
`

const footer = `
## &copy;2018 Shuo. All rights reserved.
[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2Fopenset%2Fbooks.svg?type=shield)](https://app.fossa.io/projects/git%2Bgithub.com%2Fopenset%2Fbooks?ref=badge_shield)

## License
[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2Fopenset%2Fbooks.svg?type=large)](https://app.fossa.io/projects/git%2Bgithub.com%2Fopenset%2Fbooks?ref=badge_large)
`
